GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/67b950fcd45fd505ae5fe632


###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "Amazing Person",
    "subscriber" : "Web Dev Simplified"
} 